[classification]
track_statistics = false
track_predictions = true
track_logits = true
track_probs = false # for all except due
model = 'sngp-sdn-resnet-50'
loss = 'ce'
pretrained = false
fix_seed = false
init_seed = 0
epochs = 200
batch_size = 128
test_batch_size = 10
gradient_penalty = false

[classification.optimization]
lr = 0.01
optimizer = 'sgd'
scheduler = 'multiLR'
multiLR_steps = 2
gamma = 0.2
scheduler_warmup = 'none'

[segmentation]
track_statistics = true
model = 'deeplab-v3'
loss = 'ce'
epochs = 70
batch_size = 32

[segmentation.optimization]
lr = 5e-5
optimizer = 'adam'
scheduler = 'none'
multiLR_steps = 2
gamma = 0.1

[uspec_configs]
num_seeds = 5

[uspec_configs.segmentation]
save_predictions = true
save_uspec_mean = true

[run_configs]
ensemble = -1
output_folder_name = 'run_sdn_sngp_rn50'
ld_folder_name = '/home/ryan/redo_final/LDUv1/CIFAR10/rcrop-rhflip-cutout/resnet50/paramsv0/sdn_sngp_resnet_org50v0.2.0/'
resume = 'none'
kl_loss = false
scale_ics = false
cuda = true
gpu_id = 0
train = true # when running with uspec analysis this flag will track predictions on the training set
test = true # when running with uspec analysis this flag will track predictions on the test set
val = true # only segmentation
num_lr_samples = 500
create_validation = true
scale_temperature = false

# seed range for parallel running
start_seed = 0
end_seed = 1

[run_configs.ood]
svhn = false # only classification
mnist = false # only classification
cifar10 = false # only classification
stl10 = false # only classification
cifar10C = false
cifar100 = false
cifar100C = false
cinic10 = false
medMNIST = false
curetsrC = false
imagenetC = false

[data]
dataset = 'CIFAR10' # choice between MNIST, CIFAR10 etc.
data_loc = '~/data/'

num_classes = 100
unbalance = false
pcent_unbalance = 0.5
pcent_total_unbalance = 1.0
rm_data = -0.6
create_validation = true

download = true # specifies wether to download the dataset or not

[data.augmentations]
random_crop = true
random_hflip = true
random_rotate = false # only segmentation
cutout = true # only classification

[data.seismic.sets]
training_xline = true
training_inline = true
val_xline = true
val_inline = true
test1_xline = true
test1_inline = true
test2_xline = true
test2_inline = true




